<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/07/18 17:55:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=Gonzalete',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
